package org.demo;
import org.demo.Customer;
rule "set as approve" ruleflow-group "Banker2Rule"
no-loop
when
	 $b:Customer(approve==true)
then
	modify($b){
		setApprove(true);
			}
 end

rule "set as reject" ruleflow-group "Banker2Rule"
no-loop
when
	 $b:Customer(reject==true)
then
	modify($b){
		setReject(true);
			}
 end

rule "set as rework" ruleflow-group "Banker2Rule"
no-loop
when
	 $b:Customer(rework==true)
then
	modify($b){
		setRework(true);
			}
 end

rule "set as cancel" ruleflow-group "Banker2Rule"
no-loop
when
	 $b:Customer(cancel==true)
then
	modify($b){
		setCancel(true);
			}
 end