package org.demo;
import org.demo.LoanType;
rule "set as newloan" ruleflow-group "loantype"
no-loop
when
	$p:LoanType(newloan==true)
then
	modify($p){
				setNewloan(true);
			}
end
rule "set as existingloan" ruleflow-group "loantype"
no-loop
when
	$p:LoanType(existingloan==true)
then
	modify($p){
				setExistingloan(true);
			}
end
rule "set as other" ruleflow-group "loantype"
no-loop
when
	$p:LoanType(other==true)
then
	modify($p){
				setOther(true);
			}
end