package org.demo;
import org.demo.Customer;
rule "set as new loan" ruleflow-group "LoanTypeRule"
no-loop
when
	 $p:Customer(personal==true)
then
	modify($p){
		setPersonal(true);
			}
 end

rule "set as existing loan" ruleflow-group "LoanTypeRule"
no-loop
when
	 $p:Customer(strategic==true)
then
	modify($p){
		setStrategic(true);
			}
 end

rule "set as existing loan" ruleflow-group "LoanTypeRule"
no-loop
when
	 $p:Customer(corporate==true)
then
	modify($p){
		setCorporate(true);
			}
 end
rule "set as other2" ruleflow-group "LoanTypeRule"
no-loop
when
	 $p:Customer(other2==true)
then
	modify($p){
		setOther2(true);
			}
 end