package org.demo;
import org.demo.RequestType;
rule "set as newloan" ruleflow-group "RequestTypeRule"
no-loop
when
	 $p:RequestType(newloan==true)
then
	modify($p){
		setNewloan(true);
			}
 end

rule "set as existingloan" ruleflow-group "RequestTypeRule"
no-loop
when
	 $p:RequestType(existingloan==true)
then
	modify($p){
		setExistingloan(true);
			}
 end

rule "set as other1" ruleflow-group "RequestTypeRule"
no-loop
when
	 $p:RequestType(other==true)
then
	modify($p){
		setOther(true);
			}
 end