package org.demo;
import org.demo.Customer;
rule "set as new loan" ruleflow-group "RequestTypeRule"
no-loop
when
	 $p:Customer(newloan==true)
then
	modify($p){
		setNewloan(true);
			}
 end

rule "set as existing loan" ruleflow-group "RequestTypeRule"
no-loop
when
	 $p:Customer(existingloan==true)
then
	modify($p){
		setExistingloan(true);
			}
 end

rule "set as other1" ruleflow-group "RequestTypeRule"
no-loop
when
	 $p:Customer(other1==true)
then
	modify($p){
		setOther1(true);
			}
 end