package org.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer id;
   private java.lang.String name;
   private java.lang.Integer age;
   private java.lang.String address;
   private java.lang.Integer mobilenum;
   private java.lang.Boolean female;
   private java.lang.Boolean male;
   private java.lang.Boolean newloan;
   private java.lang.Boolean existingloan;
   private java.lang.Boolean other;
   private java.lang.Boolean personal;
   private java.lang.Boolean strategic;
   private java.lang.Boolean corporate;

   public Customer()
   {
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.Integer getMobilenum()
   {
      return this.mobilenum;
   }

   public void setMobilenum(java.lang.Integer mobilenum)
   {
      this.mobilenum = mobilenum;
   }

   public java.lang.Boolean getFemale()
   {
      return this.female;
   }

   public void setFemale(java.lang.Boolean female)
   {
      this.female = female;
   }

   public java.lang.Boolean getMale()
   {
      return this.male;
   }

   public void setMale(java.lang.Boolean male)
   {
      this.male = male;
   }

   public java.lang.Boolean getNewloan()
   {
      return this.newloan;
   }

   public void setNewloan(java.lang.Boolean newloan)
   {
      this.newloan = newloan;
   }

   public java.lang.Boolean getExistingloan()
   {
      return this.existingloan;
   }

   public void setExistingloan(java.lang.Boolean existingloan)
   {
      this.existingloan = existingloan;
   }

   public java.lang.Boolean getOther()
   {
      return this.other;
   }

   public void setOther(java.lang.Boolean other)
   {
      this.other = other;
   }

   public java.lang.Boolean getPersonal()
   {
      return this.personal;
   }

   public void setPersonal(java.lang.Boolean personal)
   {
      this.personal = personal;
   }

   public java.lang.Boolean getStrategic()
   {
      return this.strategic;
   }

   public void setStrategic(java.lang.Boolean strategic)
   {
      this.strategic = strategic;
   }

   public java.lang.Boolean getCorporate()
   {
      return this.corporate;
   }

   public void setCorporate(java.lang.Boolean corporate)
   {
      this.corporate = corporate;
   }

   public Customer(java.lang.Integer id, java.lang.String name,
         java.lang.Integer age, java.lang.String address,
         java.lang.Integer mobilenum, java.lang.Boolean female,
         java.lang.Boolean male, java.lang.Boolean newloan,
         java.lang.Boolean existingloan, java.lang.Boolean other,
         java.lang.Boolean personal, java.lang.Boolean strategic,
         java.lang.Boolean corporate)
   {
      this.id = id;
      this.name = name;
      this.age = age;
      this.address = address;
      this.mobilenum = mobilenum;
      this.female = female;
      this.male = male;
      this.newloan = newloan;
      this.existingloan = existingloan;
      this.other = other;
      this.personal = personal;
      this.strategic = strategic;
      this.corporate = corporate;
   }

}