package org.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer id;
   private java.lang.Integer age;
   private java.lang.String address;
   private java.lang.Integer mobilenumber;
   private java.lang.Boolean female;
   private java.lang.Boolean male;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.Integer getMobilenumber()
   {
      return this.mobilenumber;
   }

   public void setMobilenumber(java.lang.Integer mobilenumber)
   {
      this.mobilenumber = mobilenumber;
   }

   public java.lang.Boolean getFemale()
   {
      return this.female;
   }

   public void setFemale(java.lang.Boolean female)
   {
      this.female = female;
   }

   public java.lang.Boolean getMale()
   {
      return this.male;
   }

   public void setMale(java.lang.Boolean male)
   {
      this.male = male;
   }

   public Customer(java.lang.String name, java.lang.Integer id,
         java.lang.Integer age, java.lang.String address,
         java.lang.Integer mobilenumber, java.lang.Boolean female,
         java.lang.Boolean male)
   {
      this.name = name;
      this.id = id;
      this.age = age;
      this.address = address;
      this.mobilenumber = mobilenumber;
      this.female = female;
      this.male = male;
   }

}