package org.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanType implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LoanType() {
    }

}