package org.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Newloan implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean personal;
   private java.lang.Boolean strategic;
   private java.lang.Boolean corporate;
   private java.lang.Boolean other;

   public Newloan()
   {
   }

   public java.lang.Boolean getPersonal()
   {
      return this.personal;
   }

   public void setPersonal(java.lang.Boolean personal)
   {
      this.personal = personal;
   }

   public java.lang.Boolean getStrategic()
   {
      return this.strategic;
   }

   public void setStrategic(java.lang.Boolean strategic)
   {
      this.strategic = strategic;
   }

   public java.lang.Boolean getCorporate()
   {
      return this.corporate;
   }

   public void setCorporate(java.lang.Boolean corporate)
   {
      this.corporate = corporate;
   }

   public java.lang.Boolean getOther()
   {
      return this.other;
   }

   public void setOther(java.lang.Boolean other)
   {
      this.other = other;
   }

   public Newloan(java.lang.Boolean personal, java.lang.Boolean strategic,
         java.lang.Boolean corporate, java.lang.Boolean other)
   {
      this.personal = personal;
      this.strategic = strategic;
      this.corporate = corporate;
      this.other = other;
   }

}