package org.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean newloan;
   private java.lang.Boolean existingloan;
   private java.lang.Boolean other;

   public RequestType()
   {
   }

   public java.lang.Boolean getNewloan()
   {
      return this.newloan;
   }

   public void setNewloan(java.lang.Boolean newloan)
   {
      this.newloan = newloan;
   }

   public java.lang.Boolean getExistingloan()
   {
      return this.existingloan;
   }

   public void setExistingloan(java.lang.Boolean existingloan)
   {
      this.existingloan = existingloan;
   }

   public java.lang.Boolean getOther()
   {
      return this.other;
   }

   public void setOther(java.lang.Boolean other)
   {
      this.other = other;
   }

   public RequestType(java.lang.Boolean newloan,
         java.lang.Boolean existingloan, java.lang.Boolean other)
   {
      this.newloan = newloan;
      this.existingloan = existingloan;
      this.other = other;
   }

}