package org.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer salary;

   public Employee()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getSalary()
   {
      return this.salary;
   }

   public void setSalary(java.lang.Integer salary)
   {
      this.salary = salary;
   }

   public Employee(java.lang.String name, java.lang.Integer salary)
   {
      this.name = name;
      this.salary = salary;
   }

}